version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: memoriesclub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"