
services:
  api:
    image: aula
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: memoriesclub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"