services:
  api:
    image: aula
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: memoriesclub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


#  localstack:
#    image: localstack/localstack:3.0.2
#    ports:
##      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    environment:
#      - DEBUG=${DEBUG:-0}
#
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"