version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: memoriesclub
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - C:/software/logsPostgres/db-data:/var/lib/postgresql/data