#spring:
#  datasource:
#    password: admin
#    url: jdbc:postgresql://localhost:5432/memories-club
#    username: postgres
#    datasource:
#      driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update
#        dialect: org.hibernate.dialect.PostgreSQLDialect