spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/memoriesclub
    username: admin
    datasource:
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect