management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
    enabled-by-default: 'false'
  endpoint:
    prometheus:
      enabled: 'true'
    health:
      enabled: 'true'
      show-details: always
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/memoriesclub
    datasource:
      driver-class-name: org.postgresql.Driver
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    template:
      observation-enabled: 'true'
  main:
    allow-bean-definition-overriding: true

